# https://github.com/rust-lang/rustfmt
# Configuration: https://rust-lang.github.io/rustfmt

# Stable
array_width = 50
edition = "2024"
match_block_trailing_comma = true
newline_style = "Unix"

# Nightly
binop_separator = "Back"
blank_lines_upper_bound = 3
combine_control_expr = false
force_multiline_blocks = true
group_imports = "StdExternalCrate"
imports_granularity = "One"
imports_layout = "HorizontalVertical"
reorder_impl_items = true
